---
- name: List all certificates in Common partition
  hosts: f5
  connection: local
  gather_facts: false

  vars:
    f5_host: "{{ inventory_hostname }}"
    f5_user: "{{ username }}"
    f5_password: "{{ password }}"

  tasks:
    - name: Get all certificate names
      uri:
        url: "https://{{ f5_host }}/mgmt/tm/sys/crypto/cert"
        method: GET
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        validate_certs: no
        headers:
          Content-Type: "application/json"
      register: all_certs

    - name: Get full details for each cert
      uri:
        url: "https://{{ f5_host }}/mgmt/tm/sys/crypto/cert/~Common~{{ item.name | regex_replace('^/Common/', '') | urlencode }}"
        method: GET
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        validate_certs: no
        headers:
          Content-Type: "application/json"
      loop: "{{ all_certs.json['items'] }}"
      register: cert_details

    - name: Prepare cert list for CSV (as string)
      set_fact:
        cert_csv_string: |
          Host,Name,Issuer,Expiration
          {% for cert in cert_details.results %}
          "{{ inventory_hostname }}","{{ cert.json.name | default('') }}","{{ cert.json.apiRawValues.issuer | default('') }}","{{ cert.json.apiRawValues.expiration | default('') }}"
          {% endfor %}

    - name: Write cert details to CSV (no extra collection needed)
      copy:
        dest: ./cert_list.csv
        content: "{{ cert_csv_string | trim }}"
        mode: "0644"

    # https://docs.ansible.com/ansible/latest/collections/community/general/mail_module.html
    - name: Send email
      community.general.mail:
        host: eesrelay.gov.on.ca
        port: 25
        to:
          - <daniel.yan@ontario.ca>
        cc: []
        bcc: []
        from: ansible@ontario.ca
        subject: Report on Certificates
        subtype: plain
        body: Here's the report from f5.
        attach:
          - "./cert_list.csv"
