---
- name: Get F5 pool info and members using REST API
  hosts: f5
  gather_facts: false

  vars:
    f5_server: "{{ inventory_hostname }}"
    pool_name: "Test_Pool"
    node_name: "Server_Node3"
    node_address: "10.200.0.101"
    member_port: 443

  tasks:
    - name: Get pool info from F5 REST API
      ansible.builtin.uri:
        url: "https://{{ f5_server }}/mgmt/tm/ltm/pool/{{ pool_name }}"
        method: GET
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        validate_certs: false
        return_content: yes
      register: pool_info

    - name: Show pool info
      debug:
        var: pool_info.json

    - name: Get pool member info from F5 REST API
      ansible.builtin.uri:
        url: "https://{{ f5_server }}/mgmt/tm/ltm/pool/{{ pool_name }}/members"
        method: GET
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        validate_certs: false
        return_content: yes
      register: pool_members

    - name: Show pool member info
      debug:
        var: pool_members.json['items']

    - name: Create node {{ node_name }} if it does not exist
      ansible.builtin.uri:
        url: "https://{{ f5_server }}/mgmt/tm/ltm/node"
        method: POST
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        validate_certs: false
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ node_name }}"
          address: "{{ node_address }}"
      register: add_node_result
      failed_when: add_node_result.status not in [200, 201, 409]

    - name: Add new node {{ node_name }}:{{ member_port }} to {{ pool_name }}
      ansible.builtin.uri:
        url: "https://{{ f5_server }}/mgmt/tm/ltm/pool/{{ pool_name }}/members"
        method: POST
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        validate_certs: false
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ node_name }}:{{ member_port }}"
      register: add_member_result

    - name: Show result of adding new member
      debug:
        var: add_member_result.json
